import type { IconName } from "@/blocks/icons";
import type { Accent } from "@/blocks/registry";
import type { AnimationPathPreset } from "@/animation/custom-path";

export type TemplateNode = {
  key: string;
  blockId: string;
  iconName: IconName;
  position: { x: number; y: number };
  label?: string;
  subtitle?: string;
};

export type TemplateEdge = {
  key: string;
  source: string;
  target: string;
  sourceHandle?: "top" | "right" | "bottom" | "left";
  targetHandle?: "top" | "right" | "bottom" | "left";
};

export type TemplateAnimation = {
  name: string;
  nodeKeys: string[];
  responseNodeKeys?: string[];
  colors: [string, string];
  responseColors?: [string, string];
  preset?: AnimationPathPreset;
  previewStartMs?: number;
};

export type TemplateDefinition = {
  id: string;
  name: string;
  description: string;
  iconName: IconName;
  accent: Accent;
  previewName?: string;
  edgeCurveStyle?: "stepped" | "smooth";
  width: number;
  height: number;
  nodes: TemplateNode[];
  edges: TemplateEdge[];
  animations: TemplateAnimation[];
};

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "load-balanced-web-app",
    name: "Load-balanced web app",
    description:
      "Production web delivery with edge caching, WAF, high-availability balancing, stateless application servers, cache, replicated storage, and observability.",
    iconName: "Scale",
    accent: "emerald",
    previewName: "Load-balanced requests",
    edgeCurveStyle: "smooth",
    width: 2_420,
    height: 640,
    nodes: [
      {
        key: "users",
        blockId: "service-provider",
        iconName: "Users",
        position: { x: 0, y: 260 },
        label: "Global Users",
        subtitle: "Web / Mobile",
      },
      {
        key: "cdn",
        blockId: "proxy",
        iconName: "Globe",
        position: { x: 360, y: 284 },
        label: "CDN / Edge",
        subtitle: "TLS termination & caching",
      },
      {
        key: "waf",
        blockId: "firewall",
        iconName: "ShieldNetwork",
        position: { x: 720, y: 284 },
        label: "WAF / Firewall",
        subtitle: "DDoS & rate limiting",
      },
      {
        key: "load-balancer",
        blockId: "loadbalancer",
        iconName: "Scale",
        position: { x: 1_080, y: 284 },
        label: "HA Load Balancer",
        subtitle: "Health checks & failover",
      },
      {
        key: "app-a",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 0 },
        label: "App Server A",
        subtitle: "Stateless application",
      },
      {
        key: "app-b",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 284 },
        label: "App Server B",
        subtitle: "Stateless application",
      },
      {
        key: "app-c",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 528 },
        label: "App Server C",
        subtitle: "Stateless application",
      },
      {
        key: "cache",
        blockId: "database",
        iconName: "Bolt",
        position: { x: 1_800, y: 0 },
        label: "Redis Cache",
        subtitle: "Sessions & hot data",
      },
      {
        key: "primary-db",
        blockId: "database",
        iconName: "Database",
        position: { x: 1_800, y: 284 },
        label: "PostgreSQL Primary",
        subtitle: "Transactional writes",
      },
      {
        key: "replica-db",
        blockId: "database",
        iconName: "Database",
        position: { x: 2_160, y: 284 },
        label: "PostgreSQL Replica",
        subtitle: "Read scaling & failover",
      },
      {
        key: "observability",
        blockId: "service-provider",
        iconName: "Activity2",
        position: { x: 2_160, y: 504 },
        label: "Observability",
        subtitle: "Metrics / Logs / Traces",
      },
    ],
    edges: [
      {
        key: "users-cdn",
        source: "users",
        target: "cdn",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cdn-waf",
        source: "cdn",
        target: "waf",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "waf-lb",
        source: "waf",
        target: "load-balancer",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-a",
        source: "load-balancer",
        target: "app-a",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-b",
        source: "load-balancer",
        target: "app-b",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-c",
        source: "load-balancer",
        target: "app-c",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-cache",
        source: "app-a",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-primary",
        source: "app-a",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-cache",
        source: "app-b",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-primary",
        source: "app-b",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-cache",
        source: "app-c",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-primary",
        source: "app-c",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-replica",
        source: "app-c",
        target: "replica-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "primary-replica",
        source: "primary-db",
        target: "replica-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-observability",
        source: "app-a",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-observability",
        source: "app-b",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-observability",
        source: "app-c",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Cached request via App A",
        nodeKeys: ["users", "cdn", "waf", "load-balancer", "app-a", "cache"],
        colors: ["#34d399", "#22d3ee"],
      },
      {
        name: "Write request via App B",
        nodeKeys: [
          "users",
          "cdn",
          "waf",
          "load-balancer",
          "app-b",
          "primary-db",
        ],
        colors: ["#a78bfa", "#3b82f6"],
      },
      {
        name: "Read request via App C",
        nodeKeys: [
          "users",
          "cdn",
          "waf",
          "load-balancer",
          "app-c",
          "replica-db",
        ],
        colors: ["#f59e0b", "#f97316"],
      },
      {
        name: "Primary database replication",
        nodeKeys: ["primary-db", "replica-db"],
        colors: ["#38bdf8", "#818cf8"],
      },
      {
        name: "Telemetry export",
        nodeKeys: ["app-b", "observability"],
        colors: ["#2dd4bf", "#22d3ee"],
      },
    ],
  },
  {
    id: "event-driven-commerce",
    name: "Event-driven commerce",
    description:
      "Production commerce platform with edge delivery, service isolation, transactional storage, event streaming, asynchronous workers, external providers, failure recovery, and observability.",
    iconName: "CartShopping",
    accent: "violet",
    previewName: "Commerce production flows",
    edgeCurveStyle: "smooth",
    width: 2_660,
    height: 850,
    nodes: [
      {
        key: "shoppers",
        blockId: "service-provider",
        iconName: "Users",
        position: { x: 0, y: 330 },
        label: "Global Shoppers",
        subtitle: "Web / Mobile clients",
      },
      {
        key: "edge-cdn",
        blockId: "proxy",
        iconName: "Globe",
        position: { x: 340, y: 370 },
        label: "CDN / Edge",
        subtitle: "TLS & static caching",
      },
      {
        key: "api-gateway",
        blockId: "loadbalancer",
        iconName: "Route",
        position: { x: 680, y: 370 },
        label: "API Gateway",
        subtitle: "Routing & rate limits",
      },
      {
        key: "identity",
        blockId: "container",
        iconName: "LockKeyhole",
        position: { x: 1_020, y: 0 },
        label: "Identity Service",
        subtitle: "OAuth & token validation",
      },
      {
        key: "cart",
        blockId: "container",
        iconName: "CartShopping",
        position: { x: 1_020, y: 180 },
        label: "Cart Service",
        subtitle: "Active shopping carts",
      },
      {
        key: "order",
        blockId: "container",
        iconName: "Receipt",
        position: { x: 1_020, y: 360 },
        label: "Order Service",
        subtitle: "Checkout orchestration",
      },
      {
        key: "catalog",
        blockId: "container",
        iconName: "Shop",
        position: { x: 1_020, y: 540 },
        label: "Catalog Service",
        subtitle: "Products & pricing",
      },
      {
        key: "session-cache",
        blockId: "database",
        iconName: "Key",
        position: { x: 1_360, y: 0 },
        label: "Redis Sessions",
        subtitle: "Tokens & cart state",
      },
      {
        key: "product-cache",
        blockId: "database",
        iconName: "Bolt",
        position: { x: 1_360, y: 180 },
        label: "Redis Product Cache",
        subtitle: "Hot catalog data",
      },
      {
        key: "orders-db",
        blockId: "database",
        iconName: "Database",
        position: { x: 1_360, y: 360 },
        label: "Orders PostgreSQL",
        subtitle: "Transactional source of truth",
      },
      {
        key: "event-bus",
        blockId: "server",
        iconName: "LayersAlt",
        position: { x: 1_360, y: 540 },
        label: "Kafka Event Bus",
        subtitle: "Durable domain events",
      },
      {
        key: "dead-letter",
        blockId: "database",
        iconName: "InboxArchive",
        position: { x: 1_360, y: 760 },
        label: "Dead Letter Queue",
        subtitle: "Failed event recovery",
      },
      {
        key: "payment-worker",
        blockId: "container",
        iconName: "Wallet",
        position: { x: 1_720, y: 260 },
        label: "Payment Worker",
        subtitle: "Idempotent charge processing",
      },
      {
        key: "inventory-worker",
        blockId: "container",
        iconName: "ArchiveBox",
        position: { x: 1_720, y: 480 },
        label: "Inventory Worker",
        subtitle: "Stock reservation",
      },
      {
        key: "notification-worker",
        blockId: "container",
        iconName: "Bell",
        position: { x: 1_720, y: 700 },
        label: "Notification Worker",
        subtitle: "Transactional messaging",
      },
      {
        key: "payment-provider",
        blockId: "service-provider",
        iconName: "CreditCard",
        position: { x: 2_080, y: 220 },
        label: "Payment Provider",
        subtitle: "Card network / PSP",
      },
      {
        key: "warehouse",
        blockId: "service-provider",
        iconName: "BoxArchive",
        position: { x: 2_080, y: 440 },
        label: "Warehouse / ERP",
        subtitle: "Inventory fulfillment",
      },
      {
        key: "messaging",
        blockId: "service-provider",
        iconName: "Message",
        position: { x: 2_080, y: 660 },
        label: "Email / SMS Provider",
        subtitle: "Customer notifications",
      },
      {
        key: "observability",
        blockId: "service-provider",
        iconName: "Activity2",
        position: { x: 2_420, y: 440 },
        label: "Observability",
        subtitle: "Metrics / Logs / Traces",
      },
    ],
    edges: [
      {
        key: "shoppers-cdn",
        source: "shoppers",
        target: "edge-cdn",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cdn-gateway",
        source: "edge-cdn",
        target: "api-gateway",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-identity",
        source: "api-gateway",
        target: "identity",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-cart",
        source: "api-gateway",
        target: "cart",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-order",
        source: "api-gateway",
        target: "order",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-catalog",
        source: "api-gateway",
        target: "catalog",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "identity-sessions",
        source: "identity",
        target: "session-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cart-sessions",
        source: "cart",
        target: "session-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "catalog-products",
        source: "catalog",
        target: "product-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-database",
        source: "order",
        target: "orders-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-events",
        source: "order",
        target: "event-bus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-payment",
        source: "event-bus",
        target: "payment-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-inventory",
        source: "event-bus",
        target: "inventory-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-notification",
        source: "event-bus",
        target: "notification-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-dead-letter",
        source: "event-bus",
        target: "dead-letter",
        sourceHandle: "bottom",
        targetHandle: "top",
      },
      {
        key: "payment-provider",
        source: "payment-worker",
        target: "payment-provider",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "inventory-warehouse",
        source: "inventory-worker",
        target: "warehouse",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "notification-messaging",
        source: "notification-worker",
        target: "messaging",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "identity-observability",
        source: "identity",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-observability",
        source: "order",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "payment-observability",
        source: "payment-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "inventory-observability",
        source: "inventory-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "notification-observability",
        source: "notification-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Customer checkout",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "order",
          "orders-db",
        ],
        colors: ["#34d399", "#22d3ee"],
      },
      {
        name: "Payment processing",
        nodeKeys: ["order", "event-bus", "payment-worker", "payment-provider"],
        colors: ["#a78bfa", "#ec4899"],
      },
      {
        name: "Inventory reservation",
        nodeKeys: ["order", "event-bus", "inventory-worker", "warehouse"],
        colors: ["#f59e0b", "#f97316"],
      },
      {
        name: "Customer notification",
        nodeKeys: [
          "order",
          "event-bus",
          "notification-worker",
          "messaging",
        ],
        colors: ["#38bdf8", "#818cf8"],
      },
      {
        name: "Session validation",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "identity",
          "session-cache",
        ],
        colors: ["#2dd4bf", "#22d3ee"],
      },
      {
        name: "Catalog cache lookup",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "catalog",
          "product-cache",
        ],
        colors: ["#84cc16", "#eab308"],
      },
      {
        name: "Failed event recovery",
        nodeKeys: ["order", "event-bus", "dead-letter"],
        colors: ["#fb7185", "#ef4444"],
      },
      {
        name: "Order telemetry",
        nodeKeys: ["order", "observability"],
        colors: ["#06b6d4", "#3b82f6"],
      },
    ],
  },
  {
    id: "kubernetes-production-platform",
    name: "Kubernetes production platform",
    description:
      "Production Kubernetes architecture with global routing, protected ingress, isolated workloads, stateful backing services, asynchronous jobs, autoscaling, and a complete observability stack.",
    iconName: "LayersAlt",
    accent: "sky",
    previewName: "Kubernetes production flows",
    edgeCurveStyle: "smooth",
    width: 3_040,
    height: 850,
    nodes: [
      {
        key: "users",
        blockId: "service-provider",
        iconName: "Users",
        position: { x: 0, y: 330 },
        label: "Global Users",
        subtitle: "Browser / Mobile / API",
      },
      {
        key: "dns",
        blockId: "service-provider",
        iconName: "Globe",
        position: { x: 340, y: 330 },
        label: "Global DNS",
        subtitle: "Geo routing & health checks",
      },
      {
        key: "waf",
        blockId: "firewall",
        iconName: "ShieldNetwork",
        position: { x: 680, y: 370 },
        label: "WAF / DDoS",
        subtitle: "Edge protection",
      },
      {
        key: "ingress",
        blockId: "loadbalancer",
        iconName: "Route",
        position: { x: 1_020, y: 370 },
        label: "Kubernetes Ingress",
        subtitle: "TLS & service routing",
      },
      {
        key: "auth-api",
        blockId: "container",
        iconName: "LockKeyhole",
        position: { x: 1_360, y: 80 },
        label: "Auth API",
        subtitle: "3 replicas / multi-zone",
      },
      {
        key: "web-api",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_360, y: 330 },
        label: "Web API",
        subtitle: "6 replicas / stateless",
      },
      {
        key: "admin-api",
        blockId: "container",
        iconName: "Settings",
        position: { x: 1_360, y: 580 },
        label: "Admin API",
        subtitle: "Restricted operations",
      },
      {
        key: "redis",
        blockId: "database",
        iconName: "Bolt",
        position: { x: 1_720, y: 0 },
        label: "Redis Cluster",
        subtitle: "Sessions & cache",
      },
      {
        key: "postgres",
        blockId: "database",
        iconName: "Database",
        position: { x: 1_720, y: 250 },
        label: "PostgreSQL HA",
        subtitle: "Primary + replicas",
      },
      {
        key: "kafka",
        blockId: "server",
        iconName: "LayersAlt",
        position: { x: 1_720, y: 500 },
        label: "Kafka Cluster",
        subtitle: "3 brokers / replicated",
      },
      {
        key: "worker",
        blockId: "container",
        iconName: "CpuSetting2",
        position: { x: 2_080, y: 500 },
        label: "Worker Deployment",
        subtitle: "Queue-driven autoscaling",
      },
      {
        key: "object-storage",
        blockId: "service-provider",
        iconName: "CloudStorage",
        position: { x: 2_440, y: 700 },
        label: "Object Storage",
        subtitle: "Backups & generated assets",
      },
      {
        key: "prometheus",
        blockId: "server",
        iconName: "Activity2",
        position: { x: 2_440, y: 0 },
        label: "Prometheus",
        subtitle: "Metrics & SLOs",
      },
      {
        key: "loki",
        blockId: "server",
        iconName: "ClipboardText",
        position: { x: 2_440, y: 220 },
        label: "Loki",
        subtitle: "Centralized logs",
      },
      {
        key: "tracing",
        blockId: "server",
        iconName: "RouteTrack",
        position: { x: 2_440, y: 440 },
        label: "Distributed Tracing",
        subtitle: "OpenTelemetry spans",
      },
      {
        key: "autoscaler",
        blockId: "container",
        iconName: "ChartBarTrendUp",
        position: { x: 2_800, y: 0 },
        label: "Horizontal Autoscaler",
        subtitle: "Metrics-driven replicas",
      },
      {
        key: "grafana",
        blockId: "service-provider",
        iconName: "WindowChartLine",
        position: { x: 2_800, y: 260 },
        label: "Grafana / Alerting",
        subtitle: "Dashboards & incidents",
      },
      {
        key: "alertmanager",
        blockId: "service-provider",
        iconName: "BellRing",
        position: { x: 2_800, y: 520 },
        label: "On-call Routing",
        subtitle: "Pager / Chat / Email",
      },
    ],
    edges: [
      {
        key: "users-dns",
        source: "users",
        target: "dns",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "dns-waf",
        source: "dns",
        target: "waf",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "waf-ingress",
        source: "waf",
        target: "ingress",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-auth",
        source: "ingress",
        target: "auth-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-web",
        source: "ingress",
        target: "web-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-admin",
        source: "ingress",
        target: "admin-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "auth-redis",
        source: "auth-api",
        target: "redis",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "auth-postgres",
        source: "auth-api",
        target: "postgres",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-redis",
        source: "web-api",
        target: "redis",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-postgres",
        source: "web-api",
        target: "postgres",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-kafka",
        source: "web-api",
        target: "kafka",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "admin-kafka",
        source: "admin-api",
        target: "kafka",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "kafka-worker",
        source: "kafka",
        target: "worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-postgres",
        source: "worker",
        target: "postgres",
        sourceHandle: "left",
        targetHandle: "right",
      },
      {
        key: "worker-storage",
        source: "worker",
        target: "object-storage",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-prometheus",
        source: "web-api",
        target: "prometheus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-prometheus",
        source: "worker",
        target: "prometheus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-loki",
        source: "web-api",
        target: "loki",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-loki",
        source: "worker",
        target: "loki",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-tracing",
        source: "web-api",
        target: "tracing",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-tracing",
        source: "worker",
        target: "tracing",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "metrics-autoscaler",
        source: "prometheus",
        target: "autoscaler",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "autoscaler-web",
        source: "autoscaler",
        target: "web-api",
        sourceHandle: "left",
        targetHandle: "right",
      },
      {
        key: "metrics-grafana",
        source: "prometheus",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "logs-grafana",
        source: "loki",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "traces-grafana",
        source: "tracing",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "metrics-alertmanager",
        source: "prometheus",
        target: "alertmanager",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Cached API request",
        nodeKeys: ["users", "dns", "waf", "ingress", "web-api", "redis"],
        colors: ["#34d399", "#22d3ee"],
        previewStartMs: 0,
      },
      {
        name: "Authenticated request",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "auth-api",
          "postgres",
        ],
        colors: ["#a78bfa", "#3b82f6"],
        previewStartMs: 900,
      },
      {
        name: "Asynchronous job",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "web-api",
          "kafka",
          "worker",
          "object-storage",
        ],
        colors: ["#f59e0b", "#f97316"],
        previewStartMs: 1_800,
      },
      {
        name: "Autoscaling signal",
        nodeKeys: ["web-api", "prometheus", "autoscaler", "web-api"],
        colors: ["#2dd4bf", "#22d3ee"],
        previewStartMs: 4_800,
      },
      {
        name: "Metrics dashboard",
        nodeKeys: ["web-api", "prometheus", "grafana"],
        colors: ["#84cc16", "#eab308"],
        previewStartMs: 6_000,
      },
      {
        name: "Centralized log search",
        nodeKeys: ["worker", "loki", "grafana"],
        colors: ["#38bdf8", "#818cf8"],
        previewStartMs: 6_000,
      },
      {
        name: "Distributed trace",
        nodeKeys: ["web-api", "tracing", "grafana"],
        colors: ["#d946ef", "#ec4899"],
        previewStartMs: 6_000,
      },
      {
        name: "Alert delivery",
        nodeKeys: ["worker", "prometheus", "alertmanager"],
        colors: ["#fb7185", "#ef4444"],
        previewStartMs: 7_500,
      },
      {
        name: "Administrative batch",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "admin-api",
          "kafka",
          "worker",
          "postgres",
        ],
        colors: ["#06b6d4", "#3b82f6"],
        previewStartMs: 8_500,
      },
    ],
  },
  {
    id: "sharded-postgres-platform",
    name: "Sharded PostgreSQL platform",
    description:
      "Concurrent production traffic through DNS, edge security, load balancing, application replicas, Pgpool-II, PostgreSQL shards, replicas, backups, and observability.",
    iconName: "Database",
    accent: "orange",
    previewName: "Concurrent database traffic",
    edgeCurveStyle: "smooth",
    width: 3_120,
    height: 980,
    nodes: [
      {
        key: "web-users",
        blockId: "service-provider",
        iconName: "Laptop",
        position: { x: 0, y: 180 },
        label: "Web Users",
        subtitle: "Browser traffic",
      },
      {
        key: "mobile-users",
        blockId: "service-provider",
        iconName: "Mobile",
        position: { x: 0, y: 440 },
        label: "Mobile Clients",
        subtitle: "iOS / Android traffic",
      },
      {
        key: "partner-api",
        blockId: "service-provider",
        iconName: "Code",
        position: { x: 0, y: 700 },
        label: "Partner API",
        subtitle: "External integrations",
      },
      {
        key: "dns",
        blockId: "service-provider",
        iconName: "Globe",
        position: { x: 360, y: 440 },
        label: "Authoritative DNS",
        subtitle: "Domain routing & health checks",
      },
      {
        key: "firewall",
        blockId: "firewall",
        iconName: "ShieldNetwork",
        position: { x: 720, y: 480 },
        label: "Edge Firewall",
        subtitle: "WAF / DDoS / rate limits",
      },
      {
        key: "load-balancer",
        blockId: "loadbalancer",
        iconName: "Scale",
        position: { x: 1_080, y: 480 },
        label: "Traffic Load Balancer",
        subtitle: "Health-aware routing",
      },
      {
        key: "api-a",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 180 },
        label: "API Server A",
        subtitle: "Profile & session traffic",
      },
      {
        key: "api-b",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 440 },
        label: "API Server B",
        subtitle: "Checkout & order writes",
      },
      {
        key: "api-c",
        blockId: "container",
        iconName: "BrowserCode",
        position: { x: 1_440, y: 700 },
        label: "API Server C",
        subtitle: "Reporting queries",
      },
      {
        key: "redis",
        blockId: "database",
        iconName: "Bolt",
        position: { x: 1_800, y: 0 },
        label: "Redis Session Cache",
        subtitle: "Low-latency session reads",
      },
      {
        key: "pgpool",
        blockId: "proxy",
        iconName: "Route",
        position: { x: 1_800, y: 480 },
        label: "Pgpool-II",
        subtitle: "Pooling, routing & failover",
      },
      {
        key: "shard-a",
        blockId: "database",
        iconName: "Database",
        position: { x: 2_160, y: 180 },
        label: "Customer Shard",
        subtitle: "Partition A / primary",
      },
      {
        key: "shard-b",
        blockId: "database",
        iconName: "Database",
        position: { x: 2_160, y: 440 },
        label: "Orders Shard",
        subtitle: "Partition B / primary",
      },
      {
        key: "shard-c",
        blockId: "database",
        iconName: "Database",
        position: { x: 2_160, y: 700 },
        label: "Analytics Shard",
        subtitle: "Partition C / primary",
      },
      {
        key: "replica-a",
        blockId: "database",
        iconName: "HardDrive",
        position: { x: 2_520, y: 180 },
        label: "Customer Replica",
        subtitle: "Read replica / failover",
      },
      {
        key: "replica-b",
        blockId: "database",
        iconName: "HardDrive",
        position: { x: 2_520, y: 440 },
        label: "Orders Replica",
        subtitle: "Read replica / failover",
      },
      {
        key: "replica-c",
        blockId: "database",
        iconName: "HardDrive",
        position: { x: 2_520, y: 700 },
        label: "Analytics Replica",
        subtitle: "Read replica / failover",
      },
      {
        key: "backup",
        blockId: "service-provider",
        iconName: "CloudStorage",
        position: { x: 2_880, y: 180 },
        label: "Encrypted Backups",
        subtitle: "Point-in-time recovery",
      },
      {
        key: "observability",
        blockId: "service-provider",
        iconName: "Activity2",
        position: { x: 2_880, y: 700 },
        label: "Database Observability",
        subtitle: "Queries / locks / saturation",
      },
    ],
    edges: [
      { key: "web-dns", source: "web-users", target: "dns", sourceHandle: "right", targetHandle: "left" },
      { key: "mobile-dns", source: "mobile-users", target: "dns", sourceHandle: "right", targetHandle: "left" },
      { key: "partner-dns", source: "partner-api", target: "dns", sourceHandle: "right", targetHandle: "left" },
      { key: "web-firewall", source: "web-users", target: "firewall", sourceHandle: "right", targetHandle: "left" },
      { key: "mobile-firewall", source: "mobile-users", target: "firewall", sourceHandle: "right", targetHandle: "left" },
      { key: "partner-firewall", source: "partner-api", target: "firewall", sourceHandle: "right", targetHandle: "left" },
      { key: "dns-firewall", source: "dns", target: "firewall", sourceHandle: "right", targetHandle: "left" },
      { key: "firewall-lb", source: "firewall", target: "load-balancer", sourceHandle: "right", targetHandle: "left" },
      { key: "lb-api-a", source: "load-balancer", target: "api-a", sourceHandle: "right", targetHandle: "left" },
      { key: "lb-api-b", source: "load-balancer", target: "api-b", sourceHandle: "right", targetHandle: "left" },
      { key: "lb-api-c", source: "load-balancer", target: "api-c", sourceHandle: "right", targetHandle: "left" },
      { key: "api-a-pgpool", source: "api-a", target: "pgpool", sourceHandle: "right", targetHandle: "left" },
      { key: "api-b-pgpool", source: "api-b", target: "pgpool", sourceHandle: "right", targetHandle: "left" },
      { key: "api-c-pgpool", source: "api-c", target: "pgpool", sourceHandle: "right", targetHandle: "left" },
      { key: "api-a-redis", source: "api-a", target: "redis", sourceHandle: "right", targetHandle: "left" },
      { key: "pgpool-shard-a", source: "pgpool", target: "shard-a", sourceHandle: "right", targetHandle: "left" },
      { key: "pgpool-shard-b", source: "pgpool", target: "shard-b", sourceHandle: "right", targetHandle: "left" },
      { key: "pgpool-shard-c", source: "pgpool", target: "shard-c", sourceHandle: "right", targetHandle: "left" },
      { key: "shard-a-replica", source: "shard-a", target: "replica-a", sourceHandle: "right", targetHandle: "left" },
      { key: "shard-b-replica", source: "shard-b", target: "replica-b", sourceHandle: "right", targetHandle: "left" },
      { key: "shard-c-replica", source: "shard-c", target: "replica-c", sourceHandle: "right", targetHandle: "left" },
      { key: "replica-a-backup", source: "replica-a", target: "backup", sourceHandle: "right", targetHandle: "left" },
      { key: "replica-b-backup", source: "replica-b", target: "backup", sourceHandle: "right", targetHandle: "left" },
      { key: "replica-c-backup", source: "replica-c", target: "backup", sourceHandle: "right", targetHandle: "left" },
      { key: "api-a-observability", source: "api-a", target: "observability", sourceHandle: "right", targetHandle: "left" },
      { key: "api-b-observability", source: "api-b", target: "observability", sourceHandle: "right", targetHandle: "left" },
      { key: "api-c-observability", source: "api-c", target: "observability", sourceHandle: "right", targetHandle: "left" },
    ],
    animations: [
      {
        name: "Web profile request / response",
        nodeKeys: ["web-users", "dns", "firewall", "load-balancer", "api-a", "pgpool", "shard-a"],
        responseNodeKeys: ["shard-a", "pgpool", "api-a", "load-balancer", "firewall", "web-users"],
        colors: ["#34d399", "#22d3ee"],
        responseColors: ["#38bdf8", "#818cf8"],
        preset: "request-response",
        previewStartMs: 0,
      },
      {
        name: "Mobile checkout request / response",
        nodeKeys: ["mobile-users", "dns", "firewall", "load-balancer", "api-b", "pgpool", "shard-b"],
        responseNodeKeys: ["shard-b", "pgpool", "api-b", "load-balancer", "firewall", "mobile-users"],
        colors: ["#a78bfa", "#ec4899"],
        responseColors: ["#f59e0b", "#f97316"],
        preset: "request-response",
        previewStartMs: 900,
      },
      {
        name: "Partner analytics request / response",
        nodeKeys: ["partner-api", "dns", "firewall", "load-balancer", "api-c", "pgpool", "shard-c"],
        responseNodeKeys: ["shard-c", "pgpool", "api-c", "load-balancer", "firewall", "partner-api"],
        colors: ["#facc15", "#f97316"],
        responseColors: ["#22d3ee", "#3b82f6"],
        preset: "request-response",
        previewStartMs: 1_800,
      },
      {
        name: "Cached session request / response",
        nodeKeys: ["mobile-users", "dns", "firewall", "load-balancer", "api-a", "redis"],
        responseNodeKeys: ["redis", "api-a", "load-balancer", "firewall", "mobile-users"],
        colors: ["#2dd4bf", "#84cc16"],
        responseColors: ["#60a5fa", "#a78bfa"],
        preset: "request-response",
        previewStartMs: 3_100,
      },
      {
        name: "Customer shard replication",
        nodeKeys: ["shard-a", "replica-a"],
        colors: ["#38bdf8", "#6366f1"],
        previewStartMs: 4_500,
      },
      {
        name: "Orders shard replication",
        nodeKeys: ["shard-b", "replica-b"],
        colors: ["#f59e0b", "#ef4444"],
        previewStartMs: 5_400,
      },
      {
        name: "Analytics shard replication",
        nodeKeys: ["shard-c", "replica-c"],
        colors: ["#d946ef", "#8b5cf6"],
        previewStartMs: 6_300,
      },
      {
        name: "Query telemetry export",
        nodeKeys: ["api-b", "observability"],
        colors: ["#06b6d4", "#3b82f6"],
        previewStartMs: 3_800,
      },
      {
        name: "Replica backup upload",
        nodeKeys: ["replica-c", "backup"],
        colors: ["#84cc16", "#eab308"],
        previewStartMs: 7_200,
      },
    ],
  },
];

export function findTemplate(id: string) {
  return TEMPLATES.find((template) => template.id === id);
}
