export type TemplateNode = {
  key: string;
  blockId: string;
  position: { x: number; y: number };
  label?: string;
  subtitle?: string;
};

export type TemplateEdge = {
  key: string;
  source: string;
  target: string;
  sourceHandle?: "top" | "right" | "bottom" | "left";
  targetHandle?: "top" | "right" | "bottom" | "left";
};

export type TemplateAnimation = {
  name: string;
  nodeKeys: string[];
  colors: [string, string];
};

export type TemplateDefinition = {
  id: string;
  name: string;
  description: string;
  previewName?: string;
  edgeCurveStyle?: "stepped" | "smooth";
  width: number;
  height: number;
  nodes: TemplateNode[];
  edges: TemplateEdge[];
  animations: TemplateAnimation[];
};

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "load-balanced-web-app",
    name: "Load-balanced web app",
    description:
      "Production web delivery with edge caching, WAF, high-availability balancing, stateless application servers, cache, replicated storage, and observability.",
    previewName: "Load-balanced requests",
    edgeCurveStyle: "smooth",
    width: 1_940,
    height: 640,
    nodes: [
      {
        key: "users",
        blockId: "service-provider",
        position: { x: 0, y: 260 },
        label: "Global Users",
        subtitle: "Web / Mobile",
      },
      {
        key: "cdn",
        blockId: "proxy",
        position: { x: 280, y: 284 },
        label: "CDN / Edge",
        subtitle: "TLS termination & caching",
      },
      {
        key: "waf",
        blockId: "firewall",
        position: { x: 560, y: 284 },
        label: "WAF / Firewall",
        subtitle: "DDoS & rate limiting",
      },
      {
        key: "load-balancer",
        blockId: "loadbalancer",
        position: { x: 840, y: 284 },
        label: "HA Load Balancer",
        subtitle: "Health checks & failover",
      },
      {
        key: "app-a",
        blockId: "container",
        position: { x: 1_140, y: 0 },
        label: "App Server A",
        subtitle: "Stateless application",
      },
      {
        key: "app-b",
        blockId: "container",
        position: { x: 1_140, y: 284 },
        label: "App Server B",
        subtitle: "Stateless application",
      },
      {
        key: "app-c",
        blockId: "container",
        position: { x: 1_140, y: 528 },
        label: "App Server C",
        subtitle: "Stateless application",
      },
      {
        key: "cache",
        blockId: "database",
        position: { x: 1_420, y: 0 },
        label: "Redis Cache",
        subtitle: "Sessions & hot data",
      },
      {
        key: "primary-db",
        blockId: "database",
        position: { x: 1_420, y: 284 },
        label: "PostgreSQL Primary",
        subtitle: "Transactional writes",
      },
      {
        key: "replica-db",
        blockId: "database",
        position: { x: 1_700, y: 284 },
        label: "PostgreSQL Replica",
        subtitle: "Read scaling & failover",
      },
      {
        key: "observability",
        blockId: "service-provider",
        position: { x: 1_700, y: 504 },
        label: "Observability",
        subtitle: "Metrics / Logs / Traces",
      },
    ],
    edges: [
      {
        key: "users-cdn",
        source: "users",
        target: "cdn",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cdn-waf",
        source: "cdn",
        target: "waf",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "waf-lb",
        source: "waf",
        target: "load-balancer",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-a",
        source: "load-balancer",
        target: "app-a",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-b",
        source: "load-balancer",
        target: "app-b",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "lb-app-c",
        source: "load-balancer",
        target: "app-c",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-cache",
        source: "app-a",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-primary",
        source: "app-a",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-cache",
        source: "app-b",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-primary",
        source: "app-b",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-cache",
        source: "app-c",
        target: "cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-primary",
        source: "app-c",
        target: "primary-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-replica",
        source: "app-c",
        target: "replica-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "primary-replica",
        source: "primary-db",
        target: "replica-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-a-observability",
        source: "app-a",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-b-observability",
        source: "app-b",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "app-c-observability",
        source: "app-c",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Cached request via App A",
        nodeKeys: ["users", "cdn", "waf", "load-balancer", "app-a", "cache"],
        colors: ["#34d399", "#22d3ee"],
      },
      {
        name: "Write request via App B",
        nodeKeys: [
          "users",
          "cdn",
          "waf",
          "load-balancer",
          "app-b",
          "primary-db",
        ],
        colors: ["#a78bfa", "#3b82f6"],
      },
      {
        name: "Read request via App C",
        nodeKeys: [
          "users",
          "cdn",
          "waf",
          "load-balancer",
          "app-c",
          "replica-db",
        ],
        colors: ["#f59e0b", "#f97316"],
      },
      {
        name: "Primary database replication",
        nodeKeys: ["primary-db", "replica-db"],
        colors: ["#38bdf8", "#818cf8"],
      },
      {
        name: "Telemetry export",
        nodeKeys: ["app-b", "observability"],
        colors: ["#2dd4bf", "#22d3ee"],
      },
    ],
  },
  {
    id: "event-driven-commerce",
    name: "Event-driven commerce",
    description:
      "Production commerce platform with edge delivery, service isolation, transactional storage, event streaming, asynchronous workers, external providers, failure recovery, and observability.",
    previewName: "Commerce production flows",
    edgeCurveStyle: "smooth",
    width: 2_160,
    height: 850,
    nodes: [
      {
        key: "shoppers",
        blockId: "service-provider",
        position: { x: 0, y: 330 },
        label: "Global Shoppers",
        subtitle: "Web / Mobile clients",
      },
      {
        key: "edge-cdn",
        blockId: "proxy",
        position: { x: 260, y: 370 },
        label: "CDN / Edge",
        subtitle: "TLS & static caching",
      },
      {
        key: "api-gateway",
        blockId: "loadbalancer",
        position: { x: 540, y: 370 },
        label: "API Gateway",
        subtitle: "Routing & rate limits",
      },
      {
        key: "identity",
        blockId: "container",
        position: { x: 820, y: 0 },
        label: "Identity Service",
        subtitle: "OAuth & token validation",
      },
      {
        key: "cart",
        blockId: "container",
        position: { x: 820, y: 180 },
        label: "Cart Service",
        subtitle: "Active shopping carts",
      },
      {
        key: "order",
        blockId: "container",
        position: { x: 820, y: 360 },
        label: "Order Service",
        subtitle: "Checkout orchestration",
      },
      {
        key: "catalog",
        blockId: "container",
        position: { x: 820, y: 540 },
        label: "Catalog Service",
        subtitle: "Products & pricing",
      },
      {
        key: "session-cache",
        blockId: "database",
        position: { x: 1_100, y: 0 },
        label: "Redis Sessions",
        subtitle: "Tokens & cart state",
      },
      {
        key: "product-cache",
        blockId: "database",
        position: { x: 1_100, y: 180 },
        label: "Redis Product Cache",
        subtitle: "Hot catalog data",
      },
      {
        key: "orders-db",
        blockId: "database",
        position: { x: 1_100, y: 360 },
        label: "Orders PostgreSQL",
        subtitle: "Transactional source of truth",
      },
      {
        key: "event-bus",
        blockId: "server",
        position: { x: 1_100, y: 540 },
        label: "Kafka Event Bus",
        subtitle: "Durable domain events",
      },
      {
        key: "dead-letter",
        blockId: "database",
        position: { x: 1_100, y: 760 },
        label: "Dead Letter Queue",
        subtitle: "Failed event recovery",
      },
      {
        key: "payment-worker",
        blockId: "container",
        position: { x: 1_400, y: 260 },
        label: "Payment Worker",
        subtitle: "Idempotent charge processing",
      },
      {
        key: "inventory-worker",
        blockId: "container",
        position: { x: 1_400, y: 480 },
        label: "Inventory Worker",
        subtitle: "Stock reservation",
      },
      {
        key: "notification-worker",
        blockId: "container",
        position: { x: 1_400, y: 700 },
        label: "Notification Worker",
        subtitle: "Transactional messaging",
      },
      {
        key: "payment-provider",
        blockId: "service-provider",
        position: { x: 1_700, y: 220 },
        label: "Payment Provider",
        subtitle: "Card network / PSP",
      },
      {
        key: "warehouse",
        blockId: "service-provider",
        position: { x: 1_700, y: 440 },
        label: "Warehouse / ERP",
        subtitle: "Inventory fulfillment",
      },
      {
        key: "messaging",
        blockId: "service-provider",
        position: { x: 1_700, y: 660 },
        label: "Email / SMS Provider",
        subtitle: "Customer notifications",
      },
      {
        key: "observability",
        blockId: "service-provider",
        position: { x: 1_980, y: 440 },
        label: "Observability",
        subtitle: "Metrics / Logs / Traces",
      },
    ],
    edges: [
      {
        key: "shoppers-cdn",
        source: "shoppers",
        target: "edge-cdn",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cdn-gateway",
        source: "edge-cdn",
        target: "api-gateway",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-identity",
        source: "api-gateway",
        target: "identity",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-cart",
        source: "api-gateway",
        target: "cart",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-order",
        source: "api-gateway",
        target: "order",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "gateway-catalog",
        source: "api-gateway",
        target: "catalog",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "identity-sessions",
        source: "identity",
        target: "session-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "cart-sessions",
        source: "cart",
        target: "session-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "catalog-products",
        source: "catalog",
        target: "product-cache",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-database",
        source: "order",
        target: "orders-db",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-events",
        source: "order",
        target: "event-bus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-payment",
        source: "event-bus",
        target: "payment-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-inventory",
        source: "event-bus",
        target: "inventory-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-notification",
        source: "event-bus",
        target: "notification-worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "events-dead-letter",
        source: "event-bus",
        target: "dead-letter",
        sourceHandle: "bottom",
        targetHandle: "top",
      },
      {
        key: "payment-provider",
        source: "payment-worker",
        target: "payment-provider",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "inventory-warehouse",
        source: "inventory-worker",
        target: "warehouse",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "notification-messaging",
        source: "notification-worker",
        target: "messaging",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "identity-observability",
        source: "identity",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "order-observability",
        source: "order",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "payment-observability",
        source: "payment-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "inventory-observability",
        source: "inventory-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "notification-observability",
        source: "notification-worker",
        target: "observability",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Customer checkout",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "order",
          "orders-db",
        ],
        colors: ["#34d399", "#22d3ee"],
      },
      {
        name: "Payment processing",
        nodeKeys: ["order", "event-bus", "payment-worker", "payment-provider"],
        colors: ["#a78bfa", "#ec4899"],
      },
      {
        name: "Inventory reservation",
        nodeKeys: ["order", "event-bus", "inventory-worker", "warehouse"],
        colors: ["#f59e0b", "#f97316"],
      },
      {
        name: "Customer notification",
        nodeKeys: [
          "order",
          "event-bus",
          "notification-worker",
          "messaging",
        ],
        colors: ["#38bdf8", "#818cf8"],
      },
      {
        name: "Session validation",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "identity",
          "session-cache",
        ],
        colors: ["#2dd4bf", "#22d3ee"],
      },
      {
        name: "Catalog cache lookup",
        nodeKeys: [
          "shoppers",
          "edge-cdn",
          "api-gateway",
          "catalog",
          "product-cache",
        ],
        colors: ["#84cc16", "#eab308"],
      },
      {
        name: "Failed event recovery",
        nodeKeys: ["order", "event-bus", "dead-letter"],
        colors: ["#fb7185", "#ef4444"],
      },
      {
        name: "Order telemetry",
        nodeKeys: ["order", "observability"],
        colors: ["#06b6d4", "#3b82f6"],
      },
    ],
  },
  {
    id: "kubernetes-production-platform",
    name: "Kubernetes production platform",
    description:
      "Production Kubernetes architecture with global routing, protected ingress, isolated workloads, stateful backing services, asynchronous jobs, autoscaling, and a complete observability stack.",
    previewName: "Kubernetes production flows",
    edgeCurveStyle: "smooth",
    width: 2_380,
    height: 850,
    nodes: [
      {
        key: "users",
        blockId: "service-provider",
        position: { x: 0, y: 330 },
        label: "Global Users",
        subtitle: "Browser / Mobile / API",
      },
      {
        key: "dns",
        blockId: "service-provider",
        position: { x: 260, y: 330 },
        label: "Global DNS",
        subtitle: "Geo routing & health checks",
      },
      {
        key: "waf",
        blockId: "firewall",
        position: { x: 520, y: 370 },
        label: "WAF / DDoS",
        subtitle: "Edge protection",
      },
      {
        key: "ingress",
        blockId: "loadbalancer",
        position: { x: 800, y: 370 },
        label: "Kubernetes Ingress",
        subtitle: "TLS & service routing",
      },
      {
        key: "auth-api",
        blockId: "container",
        position: { x: 1_080, y: 80 },
        label: "Auth API",
        subtitle: "3 replicas / multi-zone",
      },
      {
        key: "web-api",
        blockId: "container",
        position: { x: 1_080, y: 330 },
        label: "Web API",
        subtitle: "6 replicas / stateless",
      },
      {
        key: "admin-api",
        blockId: "container",
        position: { x: 1_080, y: 580 },
        label: "Admin API",
        subtitle: "Restricted operations",
      },
      {
        key: "redis",
        blockId: "database",
        position: { x: 1_360, y: 0 },
        label: "Redis Cluster",
        subtitle: "Sessions & cache",
      },
      {
        key: "postgres",
        blockId: "database",
        position: { x: 1_360, y: 250 },
        label: "PostgreSQL HA",
        subtitle: "Primary + replicas",
      },
      {
        key: "kafka",
        blockId: "server",
        position: { x: 1_360, y: 500 },
        label: "Kafka Cluster",
        subtitle: "3 brokers / replicated",
      },
      {
        key: "worker",
        blockId: "container",
        position: { x: 1_640, y: 500 },
        label: "Worker Deployment",
        subtitle: "Queue-driven autoscaling",
      },
      {
        key: "object-storage",
        blockId: "service-provider",
        position: { x: 1_920, y: 700 },
        label: "Object Storage",
        subtitle: "Backups & generated assets",
      },
      {
        key: "prometheus",
        blockId: "server",
        position: { x: 1_920, y: 0 },
        label: "Prometheus",
        subtitle: "Metrics & SLOs",
      },
      {
        key: "loki",
        blockId: "server",
        position: { x: 1_920, y: 220 },
        label: "Loki",
        subtitle: "Centralized logs",
      },
      {
        key: "tracing",
        blockId: "server",
        position: { x: 1_920, y: 440 },
        label: "Distributed Tracing",
        subtitle: "OpenTelemetry spans",
      },
      {
        key: "autoscaler",
        blockId: "container",
        position: { x: 2_200, y: 0 },
        label: "Horizontal Autoscaler",
        subtitle: "Metrics-driven replicas",
      },
      {
        key: "grafana",
        blockId: "service-provider",
        position: { x: 2_200, y: 260 },
        label: "Grafana / Alerting",
        subtitle: "Dashboards & incidents",
      },
      {
        key: "alertmanager",
        blockId: "service-provider",
        position: { x: 2_200, y: 520 },
        label: "On-call Routing",
        subtitle: "Pager / Chat / Email",
      },
    ],
    edges: [
      {
        key: "users-dns",
        source: "users",
        target: "dns",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "dns-waf",
        source: "dns",
        target: "waf",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "waf-ingress",
        source: "waf",
        target: "ingress",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-auth",
        source: "ingress",
        target: "auth-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-web",
        source: "ingress",
        target: "web-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "ingress-admin",
        source: "ingress",
        target: "admin-api",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "auth-redis",
        source: "auth-api",
        target: "redis",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "auth-postgres",
        source: "auth-api",
        target: "postgres",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-redis",
        source: "web-api",
        target: "redis",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-postgres",
        source: "web-api",
        target: "postgres",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-kafka",
        source: "web-api",
        target: "kafka",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "admin-kafka",
        source: "admin-api",
        target: "kafka",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "kafka-worker",
        source: "kafka",
        target: "worker",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-postgres",
        source: "worker",
        target: "postgres",
        sourceHandle: "left",
        targetHandle: "right",
      },
      {
        key: "worker-storage",
        source: "worker",
        target: "object-storage",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-prometheus",
        source: "web-api",
        target: "prometheus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-prometheus",
        source: "worker",
        target: "prometheus",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-loki",
        source: "web-api",
        target: "loki",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-loki",
        source: "worker",
        target: "loki",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "web-tracing",
        source: "web-api",
        target: "tracing",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "worker-tracing",
        source: "worker",
        target: "tracing",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "metrics-autoscaler",
        source: "prometheus",
        target: "autoscaler",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "autoscaler-web",
        source: "autoscaler",
        target: "web-api",
        sourceHandle: "left",
        targetHandle: "right",
      },
      {
        key: "metrics-grafana",
        source: "prometheus",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "logs-grafana",
        source: "loki",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "traces-grafana",
        source: "tracing",
        target: "grafana",
        sourceHandle: "right",
        targetHandle: "left",
      },
      {
        key: "metrics-alertmanager",
        source: "prometheus",
        target: "alertmanager",
        sourceHandle: "right",
        targetHandle: "left",
      },
    ],
    animations: [
      {
        name: "Cached API request",
        nodeKeys: ["users", "dns", "waf", "ingress", "web-api", "redis"],
        colors: ["#34d399", "#22d3ee"],
      },
      {
        name: "Authenticated request",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "auth-api",
          "postgres",
        ],
        colors: ["#a78bfa", "#3b82f6"],
      },
      {
        name: "Asynchronous job",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "web-api",
          "kafka",
          "worker",
          "object-storage",
        ],
        colors: ["#f59e0b", "#f97316"],
      },
      {
        name: "Autoscaling signal",
        nodeKeys: ["web-api", "prometheus", "autoscaler", "web-api"],
        colors: ["#2dd4bf", "#22d3ee"],
      },
      {
        name: "Metrics dashboard",
        nodeKeys: ["web-api", "prometheus", "grafana"],
        colors: ["#84cc16", "#eab308"],
      },
      {
        name: "Centralized log search",
        nodeKeys: ["worker", "loki", "grafana"],
        colors: ["#38bdf8", "#818cf8"],
      },
      {
        name: "Distributed trace",
        nodeKeys: ["web-api", "tracing", "grafana"],
        colors: ["#d946ef", "#ec4899"],
      },
      {
        name: "Alert delivery",
        nodeKeys: ["worker", "prometheus", "alertmanager"],
        colors: ["#fb7185", "#ef4444"],
      },
      {
        name: "Administrative batch",
        nodeKeys: [
          "users",
          "dns",
          "waf",
          "ingress",
          "admin-api",
          "kafka",
          "worker",
          "postgres",
        ],
        colors: ["#06b6d4", "#3b82f6"],
      },
    ],
  },
];

export function findTemplate(id: string) {
  return TEMPLATES.find((template) => template.id === id);
}
